const LINKS = {
first:'https://www.jungfrau.ch/en-gb/grindelwaldfirst/',firstprice:'https://www.brienzamsee.swiss/erleben/erlebnis-guide/first',
taubenloch:'https://taubenloch.ch/fr/',aare:'https://aareschlucht.ch/de/Info/informationen',
beatus:'https://shop.e-guma.ch/beatushoehlen/de/tickets/admission-st-beatus-caves-incl-cave-museum-3126879',
spiez:'https://www.dieschweizerschloesser.ch/en/our-castles/spiez-castle',gibloux:'https://fribourg.ch/fr/fribourg/architecture-et-monuments/tour-du-gibloux/',
giblouxshort:'https://www.loisirs.ch/activite/tour-du-gibloux-une-vue-a-tomber-sur-la-gruyere/',
pissevache:'https://www.valais.ch/fr/explorer/activites/sites-naturels/sites-geologiques/cascade-de-la-pissevache',
camp:'https://manorfarm.ch/fr',campprice:'https://www.manorfarm.ch/download_file/view/223/202',
zfe:'https://zfe.grandlyon.com/particulier/',card:'https://www.habkern.ch/dmxDaten/tourismus/gaesteangebote/verguenstigungen-gaestekarte-interlaken-2026.pdf',
fuel:'https://www.prix-carburants.gouv.fr/station/64360000',fx:'https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/eurofxref-graph-chf.en.html',
trient:'https://www.valleedutrient.ch/fr/gorges-du-trient-fp256'
};
const hotelUrl=(slug,start,end)=>`https://www.booking.com/hotel/${slug}.fr.html?checkin=2026-10-${start}&checkout=2026-10-${end}&group_adults=2&group_children=3&age=11&age=8&age=8&no_rooms=1&selected_currency=EUR`;
const COST_LABELS=['Logement','Gazole estimé','Péages français estimés','Vignette suisse','Stationnement / transferts','Courses et repas','Visites et télécabine'];
const DAYS=[
{id:1,date:'Samedi 24 octobre',short:'Sam. 24',nav:'Cap sur le Jura',title:'En route vers la Suisse',route:'Monein · Pontarlier',color:'#536eb8',hero:'pontarlier',heroLabel:'Pontarlier, porte Saint-Pierre',intro:'Une grande journée de route, puis une vraie nuit de repos avant les premières visites.',drive:'10–11 h',km:'≈ 1 000 km',costs:[110,195,95,0,0,40,0],
schedule:[['06:00','Départ de Monein','Petit-déjeuner et pique-nique préparés. Deux conducteurs, relais et pause environ toutes les deux heures.'],['Midi','Pause déjeuner','Prendre le temps de marcher et de laisser les enfants se dégourdir.'],['18–19 h','Arrivée à Pontarlier','Installation, dîner simple et repos. Aucune visite à caser ce soir.']],
warning:['Autour de Lyon','Passer par le contournement extérieur A46 / A432. Éviter M6, M7 et Laurent-Bonnevay avec le diesel 2010. Recalculer le trajet avant le départ.'],
lodging:{name:'Appartement saint pierre',city:'Pontarlier · 24 au 25',price:'110 €',desc:'96 m², deux chambres, cuisine, deux lits doubles et un canapé-lit. Note relevée : 8,4/10.',caveat:'Offre sur demande : réponse de l’hôte sous 24 h. Non remboursable. Option annulable relevée à 122 €. Parking à vérifier.',url:hotelUrl('fr/le-saint-pierre-pontarlier1',24,25)},
notes:'Les durées de conduite excluent les pauses. Le tracé passe par l’axe Toulouse–Montpellier, le contournement de Lyon et le Jura. Préparer les courses avant le dimanche.',sources:[['Règles de circulation à Lyon','zfe']],gallery:[],
stops:[['Monein',43.320,-.579],['Pontarlier',46.903,6.355]]},
{id:2,date:'Dimanche 25 octobre',short:'Dim. 25',nav:'Le grand panorama',title:'Au-dessus des nuages',route:'Pontarlier · Taubenloch · First · Interlaken',color:'#12796e',hero:'first',heroLabel:'First Cliff Walk, Grindelwald',intro:'Une gorge au réveil, puis la passerelle de First face aux sommets. Le grand moment du voyage.',drive:'3 h 30–4 h',km:'≈ 230 km',costs:[190.5,45,0,44,20,45,233],
schedule:[['07:30','Départ de Pontarlier','Petit-déjeuner pris et pique-nique prêt.'],['09:00','Gorges du Taubenloch','Départ à Frinvillier, retour par le même chemin. Environ 4 km, jusqu’à 10 h 30. Accès gratuit.'],['12:30','Télécabine de First','Viser le stationnement à Grindelwald vers midi. Montée en environ 25 minutes.'],['13–15:30','First Cliff Walk','Passerelle, panorama, pique-nique et courte promenade. Pas de grande randonnée ajoutée par défaut.'],['16:00','Descente puis Interlaken','Garder une heure de marge avant la dernière descente publiée, à 17 h. Installation vers 17 h.']],
warning:['First : uniquement le dimanche 25','Révision annoncée du 26 octobre au 27 novembre. En cas de retard, supprimer Taubenloch pour préserver First. En cas de mauvais temps, rester dans la vallée : environ 233 € de billets économisés.'],
lodging:{name:'New West Station 7',city:'Interlaken · nuits du 25 et du 26',price:'381 € / 2 nuits',desc:'87 m², deux chambres, cuisine et parking privé gratuit. Arrivée entre 16 h et 21 h.',caveat:'Compromis important : note 6,1/10, propreté 6,6. Non remboursable. 190,50 € affectés à chaque jour ; offre annulable pour les deux nuits : 422 €.',url:hotelUrl('ch/new-west-station-7',25,27)},
notes:'First : 2 adultes × 76 CHF + 3 enfants × 20 CHF = 212 CHF, soit environ 233 €. Cliff Walk inclus, activités supplémentaires exclues. Passage à l’heure d’hiver ce dimanche. Pour ajouter le Bachalpsee, enlever Taubenloch et vérifier neige et glace.',sources:[['Horaires First','first'],['Tarifs 2026','firstprice'],['Taubenloch','taubenloch']],gallery:[['taubenloch','Les gorges du Taubenloch']],
stops:[['Pontarlier',46.903,6.355],['Taubenloch · Frinvillier',47.168,7.252],['Grindelwald · télécabine',46.625,8.041],['First Cliff Walk',46.661,8.055],['Interlaken · 2 nuits',46.681,7.858]]},
{id:3,date:'Lundi 26 octobre',short:'Lun. 26',nav:'Gorges & lacs',title:'L’eau dans tous ses états',route:'Interlaken · Aar · Brienz · Saint-Beatus',color:'#237bba',hero:'aare',heroLabel:'Les gorges de l’Aar',intro:'Les passerelles de l’Aar, les rives du lac de Brienz et les grottes de Saint-Beatus, sans changer de logement.',drive:'1 h 45–2 h',km:'≈ 90–110 km',costs:[190.5,20,0,0,10,45,139],
schedule:[['08:45','Départ d’Interlaken','Rejoindre l’entrée ouest des gorges de l’Aar. Parking gratuit.'],['09:30','Gorges de l’Aar','Jusqu’à 11 h 15. Environ 2,8 km aller-retour sur les passerelles.'],['11:45','Pique-nique à Brienz','Pause au bord du lac, jusqu’à 13 h.'],['14:00','Grottes de Saint-Beatus','Prévoir l’approche à pied et environ une heure dans la grotte. Fin vers 16 h.'],['16:30','Retour à Interlaken','Dîner maison et temps calme.']],
warning:['Selon la pluie','Les gorges et grottes peuvent fermer en cas de fortes précipitations. Vérifier les avis d’ouverture le matin.'],
lodging:{name:'New West Station 7',city:'Interlaken · deuxième nuit',price:'190,50 € affectés',desc:'Le même appartement que la veille : pas de bagages à déplacer.',caveat:'Cette somme est la moitié de l’offre à 381 € pour les deux nuits, pas un tarif vendu à la nuit.',url:hotelUrl('ch/new-west-station-7',25,27)},
notes:'Aar : 50 CHF pour cinq. Saint-Beatus : 76 CHF pour cinq. Total environ 139 €. Carte d’hôte : réduction de 20 % à l’Aar et prix réduit aux grottes, non déduits du budget de base.',option:['Option tente + voiture','Quitter Saint-Beatus à 15 h 30, arriver à Manor Farm vers 16 h et monter la tente de jour. Environ 50–70 € pour cinq, selon la parcelle. Pas de réservation de court séjour, disponibilité sur place ; équipement adapté au froid indispensable. Avec une seule nuit d’appartement à 211 €, gain global de 100–120 €.'],sources:[['Gorges de l’Aar','aare'],['Billets Saint-Beatus','beatus'],['Carte d’hôte','card'],['Camping Manor Farm','camp']],gallery:[['beatus','L’entrée de Saint-Beatus']],
stops:[['Interlaken',46.681,7.858],['Aar · entrée ouest',46.720,8.198],['Brienz',46.754,8.037],['Saint-Beatus',46.6846,7.7821]]},
{id:4,date:'Mardi 27 octobre',short:'Mar. 27',nav:'Panoramas gratuits',title:'Des sommets au Léman',route:'Interlaken · Spiez · Gibloux · Pissevache · Thonon',color:'#bf7923',hero:'spiez',heroLabel:'Le château et la baie de Spiez',intro:'Trois des lieux repérés, sans billet d’entrée : une baie, un belvédère et une grande cascade.',drive:'4–4 h 30',km:'≈ 280–300 km',costs:[110,55,0,0,10,45,0],
schedule:[['08:30','Départ, bagages chargés','Quitter Interlaken en direction de Spiez.'],['09:00','Château et baie de Spiez','Extérieurs et parc gratuits, jusqu’à 10 h. Musée non inclus.'],['11:15','Le Gibloux','Accès court depuis Avry-devant-Pont, Route de la Tour. Parking avant la barrière. Compter 30–40 minutes de montée, la tour et le retour. Pique-nique.'],['13:00','Route vers Vernayaz','Par Bulle, Vevey / Montreux et la vallée du Rhône.'],['14:45','Cascade de Pissevache','Arrêt au pied de la chute, jusqu’à 15 h 30. Débit variable.'],['16:30','Arrivée à Thonon','Selon les pauses, arrivée entre 16 h 30 et 17 h 30, par Saint-Gingolph et Évian.']],
warning:['Choisir l’accès court au Gibloux','La boucle de 9 km depuis Sorens est trop longue pour cette journée. La tour est accessible jusqu’en octobre selon les conditions. Le repère sur la carte indique le secteur d’approche ; vérifier le parking sur place.'],
lodging:{name:'Appartement en centre ville',city:'Thonon · 27 au 28',price:'110 €',desc:'54 m², deux chambres, cuisine, deux lits simples, un double et un canapé-lit. Note 7,9/10.',caveat:'Tarif non remboursable. Option annulable relevée à 122 €. Parking à vérifier.',url:hotelUrl('fr/appartement-en-centre-ville-thonon-les-bains',27,28)},
notes:'Les gorges du Trient sont proches de Pissevache mais aucune ouverture n’est publiée ce mardi. Ne pas les ajouter au programme. Les visites retenues ici sont gratuites ; le stationnement reste budgété.',sources:[['Château de Spiez','spiez'],['Tour du Gibloux','gibloux'],['Accès court','giblouxshort'],['Pissevache','pissevache']],gallery:[['gibloux','La tour du Gibloux'],['pissevache','Cascade de Pissevache']],
stops:[['Interlaken',46.681,7.858],['Château de Spiez',46.6894,7.6874],['Gibloux · approche',46.686,7.048],['Cascade de Pissevache',46.143,7.030],['Thonon',46.374,6.480]]},
{id:5,date:'Mercredi 28 octobre',short:'Mer. 28',nav:'Dernier matin au lac',title:'Encore un peu de Léman',route:'Thonon · Clermont-Ferrand',color:'#aa5078',hero:'thonon',heroLabel:'Le port de Rives à Thonon, en automne',intro:'Une promenade au bord de l’eau puis une étape à Clermont pour couper le retour en deux.',drive:'≈ 4–5 h',km:'≈ 375 km',costs:[57,72,45,0,5,40,0],
schedule:[['09:00','Promenade au bord du Léman','Une dernière pause au lac si la météo est agréable, jusqu’à 10 h 30.'],['11:00','Départ pour Clermont-Ferrand','Contournement extérieur de Lyon, pause repas et relais au volant.'],['16–17 h','Installation et soirée tranquille','Courses, jeux et dîner à l’appartement.']],
warning:['Trajet autour de Lyon','Garder le contournement extérieur et éviter la zone interdite au diesel 2010. Les points de passage de la carte sont indicatifs : contrôler le guidage avant de partir.'],
lodging:{name:'Bulle tropicale jungle',city:'Clermont-Ferrand · 28 au 29',price:'57 €',desc:'48 m², cuisine, une chambre avec lit superposé et deux canapés-lits dans le séjour. Note 7,9/10.',caveat:'Confort simple. Non remboursable. Option annulable relevée à 63 €. Parking à vérifier.',url:hotelUrl('fr/bulle-tropicale-jungle',28,29)},
notes:'Alternative logement repérée : Appartement T3 Clermont-Ferrand, 70 m², deux chambres, 82 € ; supplément de 25 € pour une configuration plus classique.',option:['Pour réduire les péages','Départ à 8 h 30–9 h et suppression de la longue promenade du matin. Prévoir 6–7 h de conduite plus les pauses. Cette variante n’est pas le tracé coloré affiché.'],sources:[['Règles de circulation à Lyon','zfe']],gallery:[],stops:[['Thonon',46.374,6.480],['Clermont-Ferrand',45.777,3.088]]},
{id:6,date:'Jeudi 29 octobre',short:'Jeu. 29',nav:'Retour au Béarn',title:'La route des souvenirs',route:'Clermont-Ferrand · Monein',color:'#c85140',hero:'monein',heroLabel:'La place de Monein, retour au Béarn',intro:'La dernière étape, avec un retour en fin d’après-midi par le trajet rapide.',drive:'≈ 5 h 40–6 h',km:'≈ 590 km',costs:[0,113,50,0,5,35,0],
schedule:[['08:30','Départ de Clermont','Pique-nique et boissons à portée de main.'],['Matin','Route par A89 / A20','Relais au volant et pauses régulières.'],['Midi','Déjeuner et vraie pause','Garder le rythme des enfants pour cette dernière journée.'],['16–17 h','Retour à Monein','Fin de la boucle via Toulouse et A64.']],
notes:'Aucune sixième nuit à prévoir. Le budget du jour comprend la route et les repas ; la réserve de 100 € reste commune à l’ensemble du voyage.',option:['Variante sans péage','Relevé Google Maps du 9 octobre : 516 km / 7 h 52 via D1089, contre 619 km / 7 h 28 via A75. Avec les pauses, viser un retour vers 18 h 30. Variante à recalculer ; non représentée par le tracé du trajet rapide.'],sources:[],gallery:[],stops:[['Clermont-Ferrand',45.777,3.088],['Monein',43.320,-.579]]}
];
const PHOTO_LABELS={first:'First Cliff Walk',aare:'Gorges de l’Aar',spiez:'Château de Spiez',thonon:'Thonon-les-Bains',taubenloch:'Taubenloch',beatus:'Saint-Beatus',gibloux:'Tour du Gibloux',pontarlier:'Pontarlier',pissevache:'Pissevache'};
